name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: apt
      run: sudo apt update && sudo apt -y install libpng-dev libflac-dev
    - name: make
      run: make
